language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  matrix:
   - DJANGO=Django==1.11
   - DJANGO=Django==2.0
install:
 - pip install $DJANGO
 - pip install -e .
branches:
 only:
  - master
  - develop
script: python setup.py test
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=Django==2.0
    - python: "2.7"
      env: DJANGO=Django==2.0
    - python: "3.4"
      env: DJANGO=Django==1.11
    - python: "3.4"
      env: DJANGO=Django==1.11
after_success:
  - pip install --quiet python-coveralls
  - coveralls
